# -*- coding: utf-8 -*-
"""QCDF-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Dia-C1cambzheRZ2fzIf1EAO0fte_0F
"""

!unzip "Captain Tsubasa.zip"

import pandas as pd

train = pd.read_csv('train.csv')
train

f = open("output.txt", "w")
f.write(str(len(set(train['playerId'].tolist()))) + '\n')
f.write('p_18\n')
f.write('p_18,p_147\n')
f.write('71')
f.close()

goals = [0] * 160
shoots = [0] * 160
for i, row in train.iterrows():
  shoots[int(row['playerId'].split('_')[1]) - 1] += 1
  if row['outcome'] == 'گُل':
    goals[int(row['playerId'].split('_')[1]) - 1] += 1

ratio = []
for i in range(len(goals)):
  ratio.append(goals[i] / shoots[i])

import math

max = 0
for i, row in train.iterrows():
  tmp = math.sqrt(row['x'] ** 2 + row['y'] ** 2)
  if tmp > max:
    max = tmp
max